name: CI Pipeline

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Run Tests"
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry Package Manager
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Project Dependencies with Poetry
        run: |
          poetry install --with dev

      - name: Install Helm CLI
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Install helm-docs for Documentation Generation
        run: |
          HELM_DOCS_VERSION="1.14.2"
          curl -sSL "https://github.com/norwoodj/helm-docs/releases/download/v${HELM_DOCS_VERSION}/helm-docs_${HELM_DOCS_VERSION}_Linux_x86_64.tar.gz" | tar xz
          sudo mv helm-docs /usr/local/bin/

      - name: Execute Pytest Suite
        run: |
          poetry run pytest tests/

  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:') && github.ref == 'refs/heads/main'"
    needs: test
    runs-on: ubuntu-latest
    name: "Bump Version and Generate Changelog"

    permissions:
      contents: write
      actions: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Version Bump and Changelog with Commitizen
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog_increment_filename: release.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "release.md"
          tag_name: ${{ env.REVISION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
